---
apiVersion: v1
kind: Service
metadata:
  name: vllm-llama-svc
  namespace: vllm
  labels:
    app: vllm-llama
spec:
  type: ClusterIP
  selector:
    app: vllm-llama
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
